CHANGELOG = [
    {
        "version": "2.5.1",
        "date": "15.07.2026",
        "changes": [
            # ── ✨ UX формы ──────────────────────────────────────────────────────
            "ux(#form): убрана метка (мен.) у руководителей в блоке соисполнителей — роль manager больше не дублирует подпись в интерфейсе",
            "ux(#form): блок прикреплённых файлов — чекбокс удаления вызывает toggleDeleteMark(); добавлена текстовая подпись «Удалить» рядом с иконкой для ясности намерения",
            "ux(#form): визуальная отметка удаляемого файла: opacity 0.45, зачёркивание, красная рамка карточки, иконка переключается в bi-trash3-fill при отметке и обратно при снятии",
            # ── ✨ Инженерная инфраструктура ─────────────────────────────────────
            "feat(#form): водоснабжение и водоотведение разделены в разделе инженерной инфраструктуры — отдельные блоки с независимыми итогами",
            "feat(#form): добавлен блок «Водоотведение» с полем «Объём водоотведения» и строкой «Итого (отдельно от водоснабжения)»",
            # ── 🔧 JS-скрипты формы ──────────────────────────────────────────────
            "refactor(#scripts): calcWaterTotal() заменена на calcWaterSupplyTotal() и calcWaterSewageTotal() — раздельный пересчёт итогов водоснабжения и водоотведения",
            "fix(#scripts): обе функции вызываются при открытии формы (инициализация) — итоги корректно отображаются при редактировании существующего обращения",
            "fix(#scripts): атрибут oninput на всех полях водоснабжения заменён с calcWaterTotal() на calcWaterSupplyTotal(); поле водоотведения использует calcWaterSewageTotal()",
        ],
    },
    {
        "version": "2.5.0",
        "date": "09.06.2026",
        "changes": [
            # ── 🔒 Безопасность ──────────────────────────────────────────────────
            "security(#8): слабое хеширование паролей SHA-256 без соли заменено на PBKDF2-HMAC-SHA256 через werkzeug.security — плавная миграция без сброса паролей пользователей",
            "security(#61): на маршрут /login добавлен rate-limiting через flask-limiter — не более 10 попыток входа в минуту с одного IP для защиты от брутфорса",
            "security(#22): поиск возвращал данные чужих обращений без проверки роли — добавлен фильтр по created_by / can_view_all во все поисковые запросы",
            "security(#27): файл _secret.key не был исключён из Git и мог попасть в репозиторий — добавлен в .gitignore",
            "security(#21): exec() в _updater.py мог выполнить произвольный код — заменён безопасным ast.literal_eval()",
            # ── 🐛 Исправления багов ─────────────────────────────────────────────
            "fix(#63): инициализация приложения не работала при запуске через WSGI (gunicorn) — логика init вынесена из блока __main__",
            "fix(#62): коллизии имён файлов в uploads/ при загрузке одноимённых документов — добавлен префикс request_id + timestamp к имени файла",
            "fix(#60): нарушена транзакционность при загрузке файлов — несколько INSERT/UPDATE объединены в единый conn.commit()",
            "fix(#59): утечка соединений БД в inject_globals() при возникновении исключения — добавлен блок try/finally с гарантированным закрытием соединения",
            "fix(#58): право can_view_all не работало для не-администраторов из-за опечатки в ключе сессии — исправлен ключ",
            "fix(#57): функция _migrate() вызывалась при каждом вызове get_db(), что замедляло работу — добавлен флаг _migrated для однократного выполнения",
            "fix(#55): в шаблонах тёмной темы были захардкожены белые фона (#fff) — заменены на CSS-переменные для корректного отображения во всех темах",
            "fix(#36): в ocr_utils.py отсутствовала обработка ошибок в PDF/DOCX-парсерах — добавлен try/except с логированием",
            "fix(#33, #30): sync_changelog.py некорректно экранировал кавычки при записи changelog — заменено на repr() для надёжной сериализации",
            "fix(#31, #28): _updater.py вызывал save_local_sha() даже при ошибке обновления — теперь SHA сохраняется только при успешном применении патча",
            "fix(#23): dashboard.py выполнял 29+ SQL-запросов на один дашборд — оптимизировано до 6–8 запросов через агрегации",
            "fix(#12): отладочные print() в ocr_utils.py попадали в stdout и засоряли лог сервера — заменены на logging.debug()",
            "fix(#9): SECRET_KEY Flask генерировался заново при каждом рестарте, что сбрасывало сессии — вынесен в .env и читается однократно",
            "fix(#7): N+1 SQL-запросы на странице сохранённых фильтров — заменены на один UNION ALL запрос",
            "fix(#6): отсутствовали индексы на таблице requests — добавлены idx_req_status, idx_req_date и другие для ускорения фильтрации",
            "fix(#5): логика миграций БД была продублирована в 3 местах — собрана в единый источник db.py::_migrate()",
            "fix(#4): пакет easyocr отсутствовал в requirements.txt, что приводило к ImportError при установке",
            # ── ✨ Новые возможности ──────────────────────────────────────────────
            "feat(#56): массовое удаление обращений — чекбоксы в списке, плавающая панель выбора, проверка права can_delete",
            "feat(#53): новая 7-этапная цепочка статусов согласования: draft → registered → in_review → approved → rejected → completed → closed; автоприсвоение регномера при регистрации; срок рассмотрения 30 дней",
            "feat(#52): поле «Предпочтительные районы» — поиск с подсказками и мульти-выбор с тегами",
            "feat(#51): блок инженерной инфраструктуры разделён — теплоснабжение и газоснабжение вынесены в отдельные секции формы",
            "feat(#50): блок электроснабжения — JavaScript автоматически суммирует поля в строку «Общая мощность»",
            "feat(#49): блок водоснабжения — автоматическая итоговая строка «Итого м³/сут»",
            "feat(#48): инженерная инфраструктура — выбор единиц измерения для каждого поля (кВт/МВт, м³/сут и т.д.)",
            "feat(#47): поле «Право пользования» — переведено с одиночного на множественный выбор",
            "feat(#19): пагинация в списке обращений — 25 записей на страницу с навигацией",
            # ── 🔧 Рефакторинг и DevOps ──────────────────────────────────────────
            "refactor(#54): монолитный request_routes.py (32 КБ) разбит на пакет requests_app/ из 5 модулей — list_routes, form_routes, view_routes, action_routes, misc_routes",
            "refactor(#34): дублирование WHERE-фильтров в функции index() — вынесено в единую функцию _build_request_filter()",
            "chore(#35): зависимости OCR (easyocr и т.д.) вынесены в отдельный requirements-ocr.txt, не устанавливаются при базовой установке",
            "chore(#32, #29): зафиксированы точные версии всех зависимостей в requirements.txt для воспроизводимости сборки",
            "chore(#26): _updater.py доработан для работы с приватным репозиторием GitHub через Personal Access Token из .env",
            "chore(#20): .gitignore дополнен временными файлами обновлятора (_sonar_update.zip, _ocr_tmp_* и др.)",
            "chore(#17): введена структура веток main / dev / feature/* для организации разработки",
            "chore(#18, #16): настроены Issue Templates и PR Template; добавлены GitHub Actions: Ruff lint (E, W, F правила) и Gitleaks secret scanning",
            "chore(#25): добавлен SECURITY.md с политикой ответственного раскрытия уязвимостей",
            "refactor(#13): инициализация easyocr.Reader переведена на lazy-loading — Flask стартует мгновенно без ожидания загрузки OCR-модели",
            "refactor(#11): дублирующиеся GitHub-утилиты (get_latest_release, get_commits и др.) вынесены в github_utils.py",
            "chore(#10): удалены лишние зависимости pytesseract и requests, не используемые в проекте",
            # ── 🧪 OCR Beta ──────────────────────────────────────────────────────
            "feat(#4, #35, #36, #13, #12): базовый OCR-пайплайн реализован в ocr_utils.py и подключён через ai_routes.py (Blueprint ai). Поддерживает PDF, DOCX, JPG, PNG. Работает в тестовом режиме — стабильный релиз запланирован в v2.6.0",
        ],
    },
    {
        "version": "2.3.12",
        "date": "03.06.2026",
        "changes": [
            # ── Глобальный рефакторинг app.py (Этапы 1–3) ──────────────────────
            "refactor: вынести миграции в migrations.py (Этап 1.1)",
            "refactor: вынести inject_globals в context_processors.py (Этап 1.2)",
            "refactor: очистить app.py — импорты вместо встроенного кода (Этап 1.3)",
            # ── Tabulator — новый список обращений ──────────────────────────────
            "feat: подключить Tabulator 6.x CDN в base.html — серверная пагинация и сортировка (Этап 3.1)",
            "feat: создать requests_tabulator.html — список обращений на Tabulator (Этап 3.2)",
            "feat: API GET /api/requests — stats, нормализация полей, фильтры, пагинация (Этапы 2.1–3.3)",
            "feat: маршрут /requests/tabulator + POST /api/favorite (Этап 3.4)",
            "feat: bulk delete UI в requests_tabulator — чекбоксы + кнопка в тулбаре",
            # ── Динамические регистрационные номера ─────────────────────────────
            "feat(db): reg_prefix в subject_types + таблица reg_number_sequences + миграция старых ЗУ-номеров",
            "feat(action_routes): generate_request_number() — динамический номер по предмету обращения, фоллбэк БП",
            "feat(admin_routes): subject_types_write — сохранение reg_prefix при добавлении/редактировании предмета",
            "feat(templates): поле reg_prefix в форме предмета обращения (добавление + редактирование)",
            # ── ИИ-подбор площадок (WIP) ─────────────────────────────────────────
            "feat(ai): заготовка Blueprint ИИ-подбора площадок (#38) [WIP]",
            # ── Восстановление функциональности после рефакторинга ──────────────
            "feat: восстановить /impersonate/<id> и /impersonate/stop (удалены при рефакторинге Этап 1.3)",
            # ── Уведомления о новой версии / задаче в браузерной вкладке ────────
            "feat(base): flash-уведомление вкладки при наличии обновления — мигание заголовка 🆕 (Этап 1)",
            "feat(base): централизованный модуль мигания вкладки — startVersionFlashing / startTaskFlashing / stopAllFlashing (v2.20)",
            # ── Hotfixes рефакторинга (маршруты, шаблоны) ───────────────────────
            "fix: url_for('requests.index') → url_for('requests.requests_list') (BuildError after login)",
            "fix: add / redirect, /dashboard route, fix requests.index in misc_routes",
            "fix: dashboard.html url_for requests.dashboard → misc.dashboard",
            "fix: закрыть незакрытый {% if role==admin %} в конце base.html (TemplateSyntaxError)",
            "fix: исправить ссылки в таблице — просмотр /view/<id>, редактирование /request/<id>",
            "fix: remove duplicate /api/search из misc_bp (затенял search_bp)",
            "fix(info_routes): импорт ROADMAP из roadmap, не из changelog",
            "fix(sync_changelog): ROADMAP пишется в roadmap.py, не в changelog.py",
            # ── Hotfixes Tabulator (сортировка, инициализация) ───────────────────
            "fix: убрать defer у Tabulator — исправляет 'Tabulator is not defined'",
            "fix: COUNT(*) AS all → AS total (all — зарезервированное слово SQLite)",
            "fix: убрать sorter/sorterParams из колонок (конфликт с sortMode remote)",
            "fix: сортировка через dataSorting + state.sort/dir (ajaxRequestFunc не получает sorters)",
            "fix: sort через dataSorted + replaceData, locale:'default', убран sortMode remote",
            # ── Hotfixes NULL/текстовые поля БД ─────────────────────────────────
            "fix(db): миграция чистки NULL → '' в текстовых полях таблицы requests",
            "fix(form_utils): пустая строка вместо NULL для текстовых полей в build_values",
            "fix(form_routes): _PRESERVE_FIELDS проверка not val вместо is None",
            "fix(form_routes): сохранять request_files при редактировании без новых файлов",
            "fix(action_routes): текстовые поля в change_status и reviewer_decision → '' вместо NULL",
            # ── Hotfixes БД / миграции ───────────────────────────────────────────
            "fix(db): заменить SQL-комментарий -- на Python # (SyntaxError при запуске)",
            "fix(db): миграция номеров — убрана авто-замена на БП и неверный парсинг старых ЗУ-NNN-YY номеров",
            "fix(db): заполнять reg_prefix по реальным названиям БД, убрать авто-переименование",
            "fix(db): инициализация reg_number_sequences по существующим номерам — исключает дубли после миграции",
            "fix(migrations): try/finally в init_db/migrate_db; вынос миграции users в _migrate_users_cols",
            "fix(admin_routes): try/finally в classifiers(), import activity_log в топ файла",
            "fix(export_routes): try/finally в import_full, report, report_minek, export_full; пустые даты не в errors",
            "fix(view_routes): try/finally в rollback_request, убран __import__ хак",
            "fix(action_routes): guard от двойного нажатия в confirm_request — защита нумерации",
            # ── fix sidebar: точка «новая версия» ────────────────────────────────
            "fix(base): точка обновления в сайдбаре скрывается после просмотра страницы Версии (v2.20.1)",
        ],
    },
    {
        "version": "2.3.11",
        "date": "02.06.2026",
        "changes": [
            "fix: CSS-переменные статусных бейджей для тёмных тем — шаг 1 (per-theme status badge CSS vars)",
            "fix: статусные бейджи через CSS-класс без bg-*/style хаков — шаг 2",
            "fix: search.html — статусные бейджи через CSS-класс, актуальные коды статусов — шаг 3",
            "fix(dashboard.py): актуальные коды статусов, overdue_active, kpi, avg — этап 4a",
            "fix(dashboard.html): карточки ROW1 под 7 актуальных статусов — этап 4b",
            "fix(export_routes): импорт Excel создаёт новые обращения при пустом ID",
            "fix(dark-theme): checkboxes, modals, table source column — white-bg на тёмных темах",
            "fix(dark-theme): form-switch thumb SVG + inline bg overrides в users.html — v2.16",
            "feat(form): добавить id на label/input incoming_number для JS-управления",
            "feat(form): toggleIncomingNumber — обязательное поле и лейбл «№ письма СЭДО» при выборе СЭДО",
            "feat(view): динамический лейбл «№ письма СЭДО» / «№ входящего документа» в Общих сведениях",
            "fix(dark-theme) step-1: users.html — form-switch checkboxes dark/zone fix",
            "fix(dark-theme) step-2: request/new — замена хардкода #fff на var(--surface) в блоках чекбоксов",
            "fix(index): показывать created в ответе импорта + подсказка в модалке",
            "feat(requests): bulk delete route + унификация can_delete",
            "feat(templates): bulk delete UI — чекбоксы, панель, модалка",
            "fix(import) этап 1: STATUS_IMPORT_MAP + дефолт registered + request_number в COL_MAP",
            "fix(import) этап 2: дедупликация по ИНН+проект / ФИО+дата при импорте без ID",
            "feat(requests): выбор количества записей на странице 10/25/50/100",
            "fix(templates): перенос селектора per_page — правее счётчика, перед пагинацией",
            "fix(import) этап 3Б: валидация и нормализация дат (_parse_date_for_db)",
            "feat(import) этап 3А: расширенная сводка (duplicates, created_ids, status_changed)",
            "fix(import) этап 3В-1: нормализация числовых полей (_parse_numeric_for_db)",
            "fix(index): выравнивание заголовков таблицы по центру",
            "feat(import) этап 3В-2+3В-3: валидация обязательных полей и авто-номер ЗУ при импорте",
            "feat(forms,view,db): наименование полей «Наименование организации» / «Наименование проекта»; чекбокс «Проект взят на сопровождение» при закрытии + бейдж в карточке; миграция БД: колонка taken_under_supervision",
            "fix(view): исправлен Jinja url_for для reviewer_decision (сдвинута кавычка)",
            "fix(templates): возвращаем text-center на все th заголовков таблицы",
            "fix(templates): фиксируем высоту th с чекбоксом — убираем растяжение заголовка таблицы",
            "fix(templates): height/line-height только у th чекбокса, остальные th — vertical-align:middle",
        ],
    },
    {
        "version": "2.3.10",
        "date": "01.06.2026",
        "changes": [
            "feat(db): миграция 5 полей единиц измерения инфраструктуры (электро, тепло, вода, газ, канализация)",
            "feat(form_utils): unit-поля и нормализация инфраструктуры — сохранение/чтение единиц",
            "feat(form.html): input-group с выбором единицы измерения для каждого инфра-поля",
            "feat(view_routes): денормализация инфра-полей для view.html (display_vals)",
            "feat(view.html): динамические единицы инфраструктуры + display_vals",
            "feat: #47 site_right — множественный выбор (form.html + form_utils.py)",
            "feat: #49 water total autosum (Итого м³/сут)",
            "feat(#53): обновить статусы во всём UI — index.html, list_routes.py, action_routes.py",
            "fix(view.html): hotfix — register_request → assign_number, упрощена модалка регистрации",
            "fix(form_routes): preserve NOT NULL #53 fields on edit — prevent review_days NULL violation",
            "fix: перемещение OCR в раздел Прикреплённые файлы, удаление отдельной карточки OCR и кнопки из футера",
            "fix(theme): history.html — diff-del/diff-ins dark theme support",
            "fix(theme): phonebook.html — dark theme для pb-org-header, org-address-field, badge каб.",
            "fix(theme): phonebook_import_resolve.html — dark theme для org-search-results, hover, карточка опций",
            "fix(theme): roadmap.html — dark theme для roadmap-body, roadmap-icon, badge-*, roadmap-items",
            "fix(theme): classifiers.html — dark theme для result-row-selected, thead th, alert-light, nav-link.active",
        ],
    },
    {
        "version": "2.3.9",
        "date": "29.05.2026",
        "changes": [
            "Права: новое право can_investmap — доступ к разделу Инвестплощадки через настройки пользователей (не только admin)",
            "Инвестплощадки: маршруты /admin/investmap, /convert, /analyze защищены @permission_required('can_investmap') вместо @admin_required",
            "base.html v2.14: ссылка Инвестплощадки в сайдбаре видна при role==admin ИЛИ perm_can_investmap",
            "Миграция БД: колонка can_investmap INTEGER DEFAULT 0 добавлена в init_db() и migrate_db() автоматически",
            "fix: roadmap статусы idea → planned — планы снова отображаются на /changelog",
            "fix: секция Идеи → Запланировано на странице /changelog",
            "fix: пагинация в index() — добавлены PAGE_SIZE=50, page, total_pages, срез списка обращений по странице",
            "feat: список коммитов GitHub при наличии обновлений — _updater.py: get_commits_between(), info_routes.py: _fetch_commits() с кэшем, changelog.html: красивый список вместо сырого stdout",
            "fix: LOCK_FILE утечка дескрипторов, SIGTERM→os._exit(42), редирект next после логина, дедупликация BRANCH_FILE",
            "feat: phonebook-import — режим обновления дублей (update_duplicates): чекбокс Обновлять существующие контакты, UPDATE вместо пропуска, раздельная статистика",
            "feat: права can_export_full / can_import_full — полная выгрузка и импорт базы через Excel + миграция БД",
            "feat: кнопка переключения ветки main/dev перенесена в /changelog (убрана из /settings)",
            "feat: переключение ветки main/dev через UI с авторестартом (admin)",
            "fix(lint): request_routes.py — F401 удалён _int, E722/E701 раскрыт try/except в index()",
            "fix(lint): phonebook_routes.py — F401 удалён неиспользуемый импорт datetime",
            "fix(lint): login_routes.py — F401 удалён неиспользуемый импорт abort",
            "fix(lint): info_routes.py — F401 удалён неиспользуемый import signal",
            "fix(lint): make_db_template.py — F541 убран лишний f-префикс, W292 EOF",
            "fix(lint): _updater.py — W292 добавлен перевод строки в конце файла",
            "fix(lint): admin_routes.py — F401 datetime, E701/E702 разделён _build_filter_query, W292 EOF",
            "fix(lint): dashboard.py — E741 переменная l → lbl, W292 EOF",
            "fix(lint): app.py — убраны неиспользуемые импорты, разделён множественный import (F401, E401, F811)",
            "fix: нормализация заголовков портального xlsx (f2) → ключи анализатора — 36 расхождений, _normalize_portal_header(), специальная обработка координат",
            "fix: передавать active_branch в шаблон changelog",
        ],
    },
    {
        "version": "2.3.8",
        "date": "28.05.2026",
        "changes": [
            "Инвестплощадки: новый раздел /investmap — загрузка .xlsx из ГИС НСО и отображение площадок в виде текстовых карточек",
            "InvestMap: поддержка двух форматов выгрузки ГИС НСО — многообъектный (столбец B) и одиночный (3-колоночный, заголовок на 2-й строке)",
            "InvestMap: парсер Excel → структурированный текстовый блок (investmap_routes.py, Blueprint investmap_bp)",
            "InvestMap: ссылка на раздел добавлена в сайдбар для администратора",
            "Обновлятор: SHA локальной версии сохраняется только при успешном применении обновления (fix #31)",
            "Обновлятор: write_changelog() переведён на repr() вместо ручной замены кавычек — устранены ошибки при спецсимволах (fix #33)",
            "Безопасность: _secret.key добавлен в .gitignore — секретный ключ Flask не попадает в репозиторий (fix #27)",
            "Панель обновлений: автопроверка по расписанию в 12:00 и 17:00 вместо случайного setInterval(30 мин)",
            "Панель обновлений: тикающий таймер ЧЧ:ММ:СС до следующей автопроверки рядом с кнопкой «Проверить» (только для admin)",
            "Панель обновлений: убрано условие document.hidden — проверки идут всегда (лимит токена 5000 запросов/час)",
            "ROADMAP расширен: добавлены версии v3.0–v3.3 (инвестплощадки на карте, ИИ-поиск, Telegram-бот)",
            "base.html: уточнена логика ping — первые 30 сек каждые 5 сек, затем каждые 5 мин; индикатор онлайн всегда делает живую проверку",
        ],
    },
    {
        "version": "2.3.7",
        "date": "27.05.2026",
        "changes": [
            "Безопасность: exec() в sync_changelog.py заменён на ast.literal_eval() — устранена возможность выполнения произвольного кода (#21)",
            "Производительность: 5 индексов на таблицах requests и notifications — ускорение фильтрации и сортировки (#6)",
            "Производительность: N+1 запросов на /saved-filters устранён — заменён на один UNION ALL запрос (#7)",
            "OCR: print() заменён на logger.debug() в ocr_utils.py — отладочный вывод больше не попадает в stdout (#12)",
            "OCR: easyocr.Reader инициализируется лениво — Flask стартует мгновенно без ожидания загрузки модели (#13)",
            ".gitignore дополнен: временные файлы обновлятора (_sonar_update.zip, _last_commit.txt), папка Bacup/, OCR-временники (#20)",
            "Добавлен SECURITY.md с политикой ответственного раскрытия уязвимостей (#25)",
        ],
    },
    {
        "version": "2.3.6",
        "date": "27.05.2026",
        "changes": [
            "Телефонный справочник: поиск по ФИО, должности, организации и email сделан регистронезависимым для кириллицы",
            "Исправлен баг: запросы вида «зубарева», «ЗУБАРЕВА» и другие регистровые варианты теперь находят запись «Зубарева»",
            "phonebook_routes.py: в SQL-поиске добавлено приведение к нижнему регистру через LOWER(...), а поисковая строка нормализуется через search.lower()",
        ],
    },
    {
        "version": "2.3.5",
        "date": "27.05.2026",
        "changes": [
         